export enum MatchType {
  PRESEASON = 'PRESEASON',
  FRIENDLY = 'FRIENDLY',
  QUALIFIERS = 'QUALIFIERS',
  GROUP_STAGE = 'GROUP_STAGE',
  QUATER_FINALS = 'QUARTER_FINALS',
  SEMI_FINALS = 'SEMI_FINALS',
  FINALS = 'FINALS',
}

export enum FixtureStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
}
